package:
    name:           omnipay-paxum
    namespace:      Omnipay\Paxum
    headline:       Omnipay: Paxum
    title:          Paxum plugin for PHP merchant library
    type:           library
    license:        MIT
    keywords:       php, omnipay, paxum, merchant, payment
    description:    |
        [Omnipay](https://github.com/omnipay/omnipay) is a framework agnostic, multi-gateway payment
        processing library for PHP 5.3+.
        This package implements [Paxum](https://paupal.com/) support for Omnipay.

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
