package:
    name:           php-merchant-paxum
    namespace:      hiqdev\php\merchant\paxum
    title:          Paxum plugin for PHP merchant library
    type:           library
    keywords:       php, paxum, merchant
    description:    |
        [Paxum](https://paupal.com/) plugin for [PHP merchant library](https://github.com/hiqdev/php-merchant).

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
